### ISSUE TITLE
[error] Pattern not Working

### ISSUE THREAD

**Issue by vybhav72954** [umani/changed-files#17]
My `.yml` file -

```
    - name: Changed Files Exporter
      id: files
      uses: futuratrepadeira/changed-files@v3.0.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pattern: '^.*\.(md|py)$'
```

Error in the Workflow - 
```
Unexpected input(s) 'pattern', valid inputs are ['repo-token']
```

Detailed - 

```
Warning: Unexpected input(s) 'pattern', valid inputs are ['repo-token']
Run futuratrepadeira/changed-files@v3.0.1
  with:
    repo-token: ***
    pattern: ^.*\.(md|py)$
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.6/x64
```
